language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: pypi
  user: mrhwick
  password:
    secure: YWFzJ2f9hFY90LD18GziWrHgOZI0cziShU+7jzYLw7pXjJltqjOC7sEkIKboa8/eaukLNkkQdLK2v0zave0LGY0FL8r3YSbjjeB9Zin3WIcHScXyQbYDbvzFbDNNxbRFvctCLazf16RE7tAsX4LpU6nagY4ivTtkNHz5M/zb9yQ=
  on:
    tags: true
    all_branches: true
cache:
  directories:
  - /home/travis/virtualenv/python2.7/lib/python2.7/site-packages
  - /home/travis/virtualenv/python3.2/lib/python3.2/site-packages
  - /home/travis/virtualenv/python3.3/lib/python3.3/site-packages
  - /home/travis/virtualenv/python3.4/lib/python3.4/site-packages
